project:
  type: website
  resources:
    - google71dccb70fbb27a37.html

website:
  title: "Unified Field Mechanics"
  description: "Exploring the boundary of continuous wave mechanics, stroboscopic discretization, and quantum energy states."
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: UnifiedFieldMechanics_Post1.qmd
        text: Planck-Scale Dynamics
      - href: Quantum-Resonance-Mechanics-and-Macroscopic-Eigenmode-Synthesis.qmd
        text: Resonant Synthesis

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
    include-in-header: head-injections.html
    include-before-body: body-injections.html
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    code-fold: true
    code-summary: "Show Code"
    code-copy: true
    grid:
      margin-width: 350px
    reference-location: margin
    citation-location: margin
    mathjax: true
    html-math-method: mathjax
    anchor-sections: true
